# Reek configuration for SolidObserver

detectors:
  Attribute:
    exclude:
      - SolidObserver::Configuration

  TooManyInstanceVariables:
    exclude:
      - SolidObserver::Configuration

  TooManyStatements:
    exclude:
      - SolidObserver::Configuration#initialize
      - SolidObserver::Generators::InstallGenerator#show_instructions

  UtilityFunction:
    enabled: false

  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    exclude:
      - SolidObserver::Generators::InstallGenerator#show_instructions
